<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $text
 * @property string $announce
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property User $user
 */
class Post extends \yii\db\ActiveRecord
{

    const ALLOW_TAGS = "<div><a><h2><h3><h4><br><p><span><font><hr><strong><em><s><ul><li><ol><blockquote><table><th><td><tr><big><smile>";

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'title', 'text', 'announce'], 'required'],
            [['user_id', 'created_at', 'updated_at'], 'integer'],
            [['text', 'announce'], 'string'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'title' => 'Title',
            'text' => 'Text',
            'announce' => 'Announce',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function beforeSave($insert) {

        if (!$this->isNewRecord) $this->setAttribute('user_id',$this->getOldAttribute('user_id'));

        $this->text = strip_tags($this->text, self::ALLOW_TAGS);
        $this->announce = strip_tags($this->announce, self::ALLOW_TAGS);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}
